/**
 * Downloads the webfonts and writes a local @font-face stylesheet.
 *
 * Loading them from Google costs four serial round trips before a single glyph
 * can paint: DNS + TLS to fonts.googleapis.com, the CSS, then DNS + TLS to
 * fonts.gstatic.com, then the font files. That chain is what Lighthouse showed
 * at the head of the critical path, and it is why text painted in the fallback
 * at 1.0s but Largest Contentful Paint did not settle until 3.8s — the swap
 * repainted the headline late.
 *
 * Served from our own origin the connection is already warm and the files sit
 * behind the same immutable cache headers as the rest of /assets.
 *
 * Only the subsets the site can actually render are kept: latin and latin-ext
 * cover Turkish, Polish and the western European locales, cyrillic covers
 * Russian. Japanese, Chinese and Arabic fall back to system fonts either way,
 * since neither family has those glyphs.
 *
 *   node scripts/fetch-fonts.mjs      (run manually; output is committed)
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { name: 'Plus Jakarta Sans', query: 'Plus+Jakarta+Sans:wght@400;500;600;700;800' },
  { name: 'Space Grotesk', query: 'Space+Grotesk:wght@400;500;600;700' }
];

const KEEP_SUBSETS = new Set(['latin', 'latin-ext', 'cyrillic']);
const OUT_DIR = 'public/fonts';

mkdirSync(OUT_DIR, { recursive: true });

const blocks = [];
let downloaded = 0;
let skipped = 0;

for (const family of FAMILIES) {
  const res = await fetch(
    `https://fonts.googleapis.com/css2?family=${family.query}&display=swap`,
    { headers: { 'User-Agent': UA } }
  );
  const css = await res.text();

  // Each @font-face is preceded by a /* subset */ comment
  const chunks = css.split('/*').slice(1);

  for (const chunk of chunks) {
    const subset = chunk.slice(0, chunk.indexOf('*/')).trim();
    if (!KEEP_SUBSETS.has(subset)) {
      skipped++;
      continue;
    }

    const weight = chunk.match(/font-weight:\s*(\d+)/)?.[1];
    const url = chunk.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    const range = chunk.match(/unicode-range:\s*([^;]+);/)?.[1];
    if (!weight || !url) continue;

    const slug = family.name.toLowerCase().replace(/\s+/g, '-');
    const file = `${slug}-${weight}-${subset}.woff2`;

    const fontRes = await fetch(url, { headers: { 'User-Agent': UA } });
    const buf = Buffer.from(await fontRes.arrayBuffer());
    writeFileSync(join(OUT_DIR, file), buf);
    downloaded++;

    blocks.push(
      `/* ${family.name} ${weight} ${subset} */\n` +
        `@font-face {\n` +
        `  font-family: '${family.name}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('/fonts/${file}') format('woff2');\n` +
        (range ? `  unicode-range: ${range.trim()};\n` : '') +
        `}`
    );
  }
}

writeFileSync(
  'src/fonts.css',
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n${blocks.join('\n\n')}\n`,
  'utf8'
);

console.log(`fonts: ${downloaded} files written, ${skipped} subsets skipped`);
